# This is an example distribution file for PedSilicoICH simulations
# All parameters are given as a list which is sampled from in the `recruit` program
#
# uncommented parameters here will override defaults
[general]
output_directory=" /projects01/didsr-aiml/brandon.nelson/pedsilicoICH/InSilicoICH5k"
# scan_coverage=[0, 10]  # scan range in mm, min max, comment out to scan whole range
study_count=5000  # desired dataset size
remove_raw=true  # keep projection data
seed=42  # seed to reproduce dataset, set to false or integer

[patient]
age=[0, 100]  # range in yrs [min, max]

[lesion]
subtype=[false, 'IPH', 'SDH', 'EDH', 'IVH', 'SAH'] # add [false] for hemorrhage-absent cases
mass_effect=true  # whether lesions displace brain tissue
edema=[0, 15]  # edema width range [min, max] in pixels
lesion_volume='src/insilicoICH/distributions/BHSD_volume_distributions.csv'  # str or list
lesion_attenuation='src/insilicoICH/distributions/BHSD_HU_distributions.csv'  # str or list

[acquisition]
scanner_model=['Siemens_DefinitionFlash', 'GE_Lightspeed64']
views=[100]
kVp=[100, 120, 140]  # Tube potential: The electric potential applied across an x-ray tube to accelerate electrons towards a target material, expressed in units of kilovolts (kV) 
mA=[100, 150, 200, 250]  # Tube current: Number of electrons accelerated across an x-ray tube per unit time, expressed in units of milliampere (mA)
pitch=[0]  # pitch = 0 for axial model, pitch > 0 for helical, recommend pitch < 0.6 for head
#  Unitless parameter used to describe the table travel during helical CT; equal to table travel (mm) per gantry rotation ÷ total nominal beam width (mm) 

[recon]
recon_kernel=['standard', 'soft']  # Reconstruction property that determines sharpness or smoothness of image in the axial plane 
slice_thickness=[1, 3, 5]  # Nominal width of reconstructed image along the z axis 
slice_increment=[1]  # Distance between adjacent slices in the z axis, should be equal to or greater than slice thickness